C2PA-250: Update to the branch with the fix from the SDK.
Monotype/c2patool pull request #10
Opened 2023-08-15 17:16 UTC by brogdonm

# JIRA Issue

- https://monotype.atlassian.net/browse/C2PA-250

# Checklist

- [x] **PR labeled** appropriately
- [ ] **Documentation** updated:
  - [ ] Developer documentation (ReadMe files)
  - [ ] Product documentation (Release notes, PDK Guide, Functional Spec, API documents, ...)
- [ ] **Test case(s)** added
  - [ ] Unit Tests

# Notes for Reviewers

References the latest fixes in the SDK for regression issue of rewinding the input stream. Depends on: https://github.com/Monotype/c2pa-rs/pull/14

# Verification Instructions

Should test out signing a font with and without a remote manifest.

```
cargo run -- ..\HELVETICANOWMTTEXT.OTF --manifest manifest.json --output ..\HELVETICANOWMTTEXT.signed.OTF --force
```

And see help usage for `--remote`.

> Actively maintained by the @Monotype/driverpdldev team.

2023-08-15 22:10 UTC, chriskushmonotype reviewed
?

2023-08-15 22:10 UTC, chriskushmonotype commented on Cargo.toml
> +#c2pa = { path="../c2pa-rs/sdk", features=["otf", "fetch_remote_manifests", "file_io", "add_thumbnails", "xmp_write"] }
Intentional? I don't mind, necessarily, though a comment might be tidy.

2023-08-15 22:48 UTC, chriskushmonotype requested changes
hmm actually yeah, this is unwelcome if we really wanna flow back upstream, right?

2023-08-15 22:57 UTC, brogdonm commented on Cargo.toml
> +#c2pa = { path="../c2pa-rs/sdk", features=["otf", "fetch_remote_manifests", "file_io", "add_thumbnails", "xmp_write"] }
No, not intentional. I removed, thanks.

2023-08-15 22:58 UTC, brogdonm commented
> hmm actually yeah, this is unwelcome if we really wanna flow back upstream, right?

Agreed, removed.

2023-08-16 19:35 UTC, chriskushmonotype approved these changes
Poifection!

2023-08-16 20:28 UTC, merged